"""v1.0

Revision ID: 44e0c9aef94
Revises: 51f5ccfba190
Create Date: 2017-05-02 14:42:45.291019

"""

# revision identifiers, used by Alembic.
revision = '44e0c9aef94'
down_revision = '51f5ccfba190'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
